### PR TITLE
ARM64

### PR DESCRIPTION
**Pull request by DarekDevv**
Arm64 binaries 5.7.4.0

### CODE REVIEW

**Comment by pp-r** [comment]
Hello,

I've also done things here :
https://github.com/pp-r/simplex_ynh/releases/tag/v5.7.4

**Review by pp-r — CHANGES_REQUESTED** [review]
Hello,
You should add another change to the manifest on line 8 :
```version = "5.7.1~ynh1"``` to ```version = "5.7.1~ynh2"```

**Comment by pp-r** [comment]
Hello @ericgaspar ,

When you build for amd64, could you let us know with ```ghcup tui``` what are the versions of each tools you use ?
https://www.haskell.org/ghcup/install/#supported-tools

Thanks !

**Comment by DarekDevv** [comment]
> Hello,
> 
> I've also done things here : https://github.com/pp-r/simplex_ynh/releases/tag/v5.7.4
> 
> Edit : I've made a backup that i've downloaded before testing it on my arm64 testing plateform. I've test on my side and it works for messaging (in/out), call (out), video call (in/out) and send an image (out)
> 
> > sudo yunohost app upgrade simplex -u https://github.com/pp-r/simplex_ynh
> 
> simplex_ynh_571ynh2
> 
> This will certainly require more testing than just what I've been able to do somewhat randomly.
> 
> Edit 2 : No goods news :-( Today services won't start : simplex https://paste.yunohost.org/loyetejesi xftp https://paste.yunohost.org/oqimucirah.yaml `/usr/local/bin/simplex/xftp-server: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory`

Need openssl 3!

**Comment by pp-r** [comment]
Hello,

I've rebuild on the basis of RaspiOS Bullseye in order to build with an OS using OpenSSL1.
I've done `sudo yunohost app upgrade simplex -u https://github.com/pp-r/simplex_ynh/tree/master --debug` then `reboot` and the services appear to be operating correctly and the diagnosis don't complain about.

**Comment by ericgaspar** [comment]
closing with #26

**Pull request closed without merging**
