### PR TITLE
V5.8.0

### PR DESCRIPTION
**Pull request by pp-r**
## Problem

- *A new stable release version is out v5.8.0*

## Solution

- *Update from v5.7.5 to v5.8.0 in testing branch*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by pp-r** [comment]
!gogogadgetoci

**Comment by ericgaspar** [comment]
Thanks for builing the binaries. You should be able to upload your binaries to the app repo now.

**Comment by pp-r** [comment]
It's a pre-release :
https://github.com/simplex-chat/simplex-chat/releases/tag/v5.8.0
So it would be better to merge in the testing branch.

**Comment by pp-r** [comment]
Hello,

Now that v5.8.0 is in stable release, i've uploaded the binaries to the app repo :
https://github.com/simplex-chat/simplexmq/releases/tag/v5.8.0

!gogogadgetoci

**Comment by pp-r** [comment]
!gogogadgetoci

**Comment by ericgaspar** [comment]
Thanks for your help!

**Pull request merged**
